Repository jrasell/sherpa, pull requests merged in 2019-10, with the labels that each got.

#58 Move Nomad Meta policy to satisfy policy interface.
  cmd/server/command.go
  go.mod
  pkg/policy/backend/nomadmeta/consts.go
  pkg/policy/backend/nomadmeta/nomadmeta.go
  pkg/policy/backend/nomadmeta/processor.go
  pkg/policy/backend/nomadmeta/processor_test.go
  pkg/policy/watcher/meta_keys.go
  pkg/policy/watcher/watcher_test.go
  pkg/server/routes.go
  pkg/server/server.go
  pkg/watcher/job/job.go
Labels: area/policy-engine, area/policy-storage, kind/bug

#61 Fix makefile test target by rename to tests to avoid dir conflict.
  GNUmakefile
Labels: kind/bug

#62 Fix incorrect response code and msg when scaling breaks thresholds
  pkg/scale/scale.go
  test/scale_in_test.go
  test/scale_out_test.go
Labels: area/api, area/scaling, kind/bug

#64 docs: add high availability feature documentation.
  docs/api/README.md
  docs/api/system.md
  docs/configuration/README.md
  docs/guides/high-availability.md
Labels: area/copy, kind/enhancement

#65 server: remove leader protection from all system routes.
  pkg/server/routes.go
Labels: kind/bug

#66 Release v0.2.0
  CHANGELOG.md
  Dockerfile
  README.md
Labels: kind/enhancement

#69 endpoint: fix malformed server log messages.
  pkg/scale/v1/scale.go
Labels: area/api, kind/bug

#71 Fix issue when autoscaling job with mix of groups w/wo policies.
  pkg/autoscale/autoscale.go
Labels: area/autoscaling, kind/bug

#72 mod/vendor: update panjf2000/ants to latest v2 release.
  go.mod
  go.sum
  pkg/autoscale/handler.go
  vendor/github.com/panjf2000/ants/go.mod
  vendor/github.com/panjf2000/ants/v2/.gitignore
  vendor/github.com/panjf2000/ants/v2/.travis.yml
  vendor/github.com/panjf2000/ants/v2/CODE_OF_CONDUCT.md
  vendor/github.com/panjf2000/ants/v2/CONTRIBUTING.md
  vendor/github.com/panjf2000/ants/v2/LICENSE
  vendor/github.com/panjf2000/ants/v2/README.md
  vendor/github.com/panjf2000/ants/v2/README_ZH.md
  vendor/github.com/panjf2000/ants/v2/ants.go
  vendor/github.com/panjf2000/ants/v2/go.mod
  vendor/github.com/panjf2000/ants/v2/internal/spinlock.go
  vendor/github.com/panjf2000/ants/v2/pool.go
  vendor/github.com/panjf2000/ants/v2/pool_func.go
  vendor/github.com/panjf2000/ants/v2/worker.go
  vendor/github.com/panjf2000/ants/v2/worker_func.go
  vendor/modules.txt
Labels: kind/enhancement

#73 Release v0.2.1
  CHANGELOG.md
  Dockerfile
  README.md
Labels: kind/enhancement

#75 added job count and direction to webui
  pkg/server/endpoints/v1/ui.go
Labels: kind/enhancement

#78 Add numiralofe to README.md contributors.
  README.md
Labels: area/copy, kind/enhancement

#74 pkg/state: add metadata to scaling events
  cmd/scale/in/command.go
  cmd/scale/out/command.go
  pkg/api/scale.go
  pkg/autoscale/autoscale.go
  pkg/config/scale/scale.go
  pkg/scale/consts.go
  pkg/scale/event.go
  pkg/scale/scale.go
  pkg/scale/v1/scale.go
  pkg/state/scale.go
  pkg/state/scale/consul/consul.go
  pkg/state/scale/memory/memory.go
  pkg/state/scale/memory/memory_test.go
  test/scale_in_test.go
  test/scale_out_test.go
Labels: area/api, area/cli, kind/enhancement

#79 style(meta): wrong copy paste
  pkg/policy/backend/nomadmeta/processor.go
Labels: kind/cleanup

#82 Add commarla to README contributors listing.
  README.md
Labels: area/copy, kind/enhancement

#77 Add cooldown functionality to scaling policies and storage backend.
  cmd/policy/init/command.go
  cmd/policy/list/command.go
  cmd/policy/read/command.go
  pkg/api/policy.go
  pkg/autoscale/autoscale.go
  pkg/autoscale/handler.go
  pkg/policy/backend/nomadmeta/consts.go
  pkg/policy/backend/nomadmeta/processor.go
  pkg/policy/backend/nomadmeta/processor_test.go
  pkg/policy/policy.go
  pkg/policy/v1/policies_test.go
  pkg/policy/validate.go
  pkg/policy/validate_test.go
  pkg/scale/consts.go
  pkg/scale/cooldown.go
  pkg/scale/cooldown_test.go
  pkg/scale/event.go
  pkg/scale/v1/consts.go
  pkg/scale/v1/scale.go
  pkg/state/scale/backend.go
  pkg/state/scale/consul/consul.go
  pkg/state/scale/memory/memory.go
  test/scale_in_test.go
  test/scale_out_test.go
Labels: area/scaling, kind/enhancement

#83 cluster: fix a big where cluster state get overwritten on restart.
  pkg/server/cluster/cluster.go
  pkg/server/cluster/member.go
Labels: kind/bug
