Repository jrasell/sherpa, pull requests merged in 2019-09, with the labels that each got.

#35 Ensure go mod is not enabled when install makefile tools.
  GNUmakefile
Labels: kind/bug

#33 Add simple UI to provide visual overview of scaling events.
  pkg/config/server/server.go
  pkg/config/server/server_test.go
  pkg/server/config.go
  pkg/server/endpoints/v1/ui.go
  pkg/server/routes.go
Labels: area/autoscaling, area/scaling, kind/enhancement

#36 Autoscaler log to debug when it suggests a group should be scaled.
  pkg/autoscale/autoscale.go
Labels: area/autoscaling, kind/bug

#38 Update docs to reference new web UI feature with image example.
  docs/assets/web_ui_overview.png
  docs/configuration/README.md
  docs/guides/ui.md
Labels: area/copy

#39 Fix style issue where scale cmd helped ended with fullstop.
  cmd/scale/in/command.go
  cmd/scale/out/command.go
Labels: area/cli, kind/bug

#40 Add documentation for new scaling state feature.
  docs/api/scale.md
  docs/commands/scale.md
  docs/configuration/README.md
  docs/guides/README.md
  docs/guides/autoscaler.md
  docs/guides/policies.md
  docs/guides/scaling-state.md
  docs/guides/storage.md
  docs/guides/strict-checking.md
Labels: area/copy

#41 Update system info to reference more generic storage backend.
  cmd/system/info/command.go
  docs/api/system.md
  pkg/api/system.go
  pkg/system/v1/system.go
  pkg/system/v1/system_test.go
Labels: area/policy-storage, kind/enhancement

#43 Release v0.1.0.
  CHANGELOG.md
  Dockerfile
  README.md
Labels: kind/enhancement

#46 Add contributors section to README to list user links.
  README.md
Labels: area/copy, kind/enhancement

#45 Add Sherpa cluster leadership allowing HA server deployments.
  cmd/server/command.go
  cmd/system/command.go
  cmd/system/leader/command.go
  go.mod
  go.sum
  pkg/api/system.go
  pkg/autoscale/handler.go
  pkg/config/server/cluster.go
  pkg/config/server/cluster_test.go
  pkg/server/cluster/cluster.go
  pkg/server/cluster/cluster_test.go
  pkg/server/cluster/leader.go
  pkg/server/cluster/member.go
  pkg/server/config.go
  pkg/server/gc.go
  pkg/server/handler.go
  pkg/server/router/router.go
  pkg/server/routes.go
  pkg/server/server.go
  pkg/state/cluster.go
  pkg/state/cluster/backend.go
  pkg/state/cluster/consul/consul.go
  pkg/state/cluster/memory/memory.go
  pkg/system/v1/system.go
  pkg/system/v1/system_test.go
  vendor/github.com/oklog/run/.gitignore
  vendor/github.com/oklog/run/.travis.yml
  vendor/github.com/oklog/run/LICENSE
  vendor/github.com/oklog/run/README.md
  vendor/github.com/oklog/run/group.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/modules.txt
Labels: kind/enhancement

#50 Fix panic within the cluster memory backend.
  pkg/state/cluster/memory/memory.go
Labels: kind/bug

#48 Add quick-start demo to the docs guide.
  docs/guides/README.md
Labels: area/copy, kind/enhancement

#51 backend/consul: fix job group policy list
  pkg/policy/backend/consul/consul.go
Labels: area/policy-engine, area/policy-storage, kind/bug

#52 pkg/api: accept JobGroupPolicy type for Write
  cmd/policy/write/command.go
  pkg/api/policy.go
Labels: area/api, area/policy-engine, kind/bug

#53 pkg/policy: fix panic in get policy by job and group
  pkg/policy/backend/consul/consul.go
  pkg/policy/v1/policies.go
Labels: area/policy-storage, kind/bug

#54 test: establish acceptance tests for policy API
  GNUmakefile
  test/acctest/acctest.go
  test/acctest/helpers.go
  test/policy_test.go
Labels: area/testing, kind/enhancement

#57 Policy meta watcher should start index at 1, not 0.
  pkg/policy/watcher/watcher.go
Labels: area/policy-engine, kind/bug

#56 Do not scale a job group when it is in deployment.
  go.mod
  pkg/autoscale/handler.go
  pkg/scale/consts.go
  pkg/scale/deployments.go
  pkg/scale/deployments_test.go
  pkg/scale/scale.go
  pkg/scale/v1/consts.go
  pkg/scale/v1/scale.go
  pkg/server/routes.go
  pkg/server/server.go
  pkg/watcher/deployment/deployment.go
  pkg/watcher/watcher.go
  pkg/watcher/watcher_test.go
Labels: area/autoscaling, area/scaling, kind/enhancement
