Repository jrasell/sherpa, pull requests merged in 2019-07, with the labels that each got.

#9 Internal autoscaling thresholds are now configurable within policy.
  cmd/policy/init/command.go
  pkg/api/policy.go
  pkg/autoscale/autoscale.go
  pkg/autoscale/config.go
  pkg/policy/backend/memory/memory_test.go
  pkg/policy/policy.go
  pkg/policy/v1/policies_test.go
  pkg/policy/validate.go
  pkg/policy/validate_test.go
  pkg/policy/watcher/consts.go
  pkg/policy/watcher/meta_keys.go
  pkg/policy/watcher/meta_keys_test.go
  pkg/policy/watcher/watcher.go
  pkg/policy/watcher/watcher_test.go
Labels: area/autoscaling, area/policy-engine, kind/enhancement

#10 Upadte docs to reference new auto-scaling policy thresholds.
  docs/api/policy.md
  docs/guides/policies.md
Labels: area/copy, kind/enhancement

#11 Fix incorrect error message return within Consul backend.
  pkg/policy/backend/consul/consul.go
Labels: area/policy-storage, kind/bug

#17 Update resource usage calculation to multiply first and then divide
  pkg/autoscale/autoscale.go
Labels: area/autoscaling, kind/bug

#18 Filter out the allocations from ResourceTracker that aren't actively running or pending
  pkg/autoscale/autoscale.go
Labels: area/autoscaling, kind/bug
