Repository jrasell/sherpa, pull requests merged in 2019-05, with the labels that each got.

#1 docs: add missing quote marks
  docs/api/scale.md
Labels: area/copy, kind/bug

#3 Add metrics API endpoint and CLI command
  cmd/system/command.go
  cmd/system/metrics/command.go
  docs/api/system.md
  docs/commands/system.md
  go.mod
  go.sum
  pkg/api/system.go
  pkg/server/config.go
  pkg/server/routes.go
  pkg/server/server.go
  pkg/server/telemetry.go
  pkg/system/v1/system.go
  pkg/system/v1/system_test.go
  vendor/gopkg.in/square/go-jose.v2/LICENSE
  vendor/gopkg.in/square/go-jose.v2/json/LICENSE
  vendor/gopkg.in/square/go-jose.v2/json/README.md
  vendor/gopkg.in/square/go-jose.v2/json/decode.go
  vendor/gopkg.in/square/go-jose.v2/json/encode.go
  vendor/gopkg.in/square/go-jose.v2/json/indent.go
  vendor/gopkg.in/square/go-jose.v2/json/scanner.go
  vendor/gopkg.in/square/go-jose.v2/json/stream.go
  vendor/gopkg.in/square/go-jose.v2/json/tags.go
  vendor/modules.txt
Labels: area/api, area/cli, kind/enhancement

#4 The docs README should link to docs directory, not dir readme.
  docs/README.md
Labels: area/copy, kind/enhancement

#5 Update CHANGELOG to set 0.0.1 release date.
  CHANGELOG.md
Labels: area/copy, kind/enhancement

#6 Update README and Dockerfile binary links based on v0.0.1 release.
  Dockerfile
  README.md
Labels: area/copy, kind/bug
