Repository jrasell/sherpa, pull requests merged in 2020-01, with the labels that each got.

#121 Fix incorrect searching of allocs causing missed allocs in jobs.
  pkg/autoscale/nomad.go
Labels: area/autoscaling, kind/bug

#122 Prepare for v0.4.1 release.
  CHANGELOG.md
  Dockerfile
  README.md
Labels: area/build, kind/enhancement

#124 Add pprof Debug routes for Sherpa server profiling.
  cmd/server/command.go
  docs/configuration/README.md
  pkg/config/server/debug.go
  pkg/config/server/debug_test.go
  pkg/server/config.go
  pkg/server/routes.go
Labels: kind/enhancement

#128 autoscale: pass group name to calculateExternalScalingDecision
  pkg/autoscale/autoscale.go
Labels: area/autoscaling, kind/bug

#129 Add @hobochili to README contributors list.
  README.md
Labels: area/copy, kind/enhancement
